### PR TITLE
🐛 Fix issue template `ossf` link

### PR DESCRIPTION
**Pull request by lelia**
Fixes the `issue.ejs` template to use the correct `ossf/scorecard-monitor` link as seen in `report.ejs`.

Refs: #75, #79.

### CODE REVIEW

**Comment by lelia** [comment]
Hey @UlisesGascon — I couldn't find any dev setup instructions in `README.md` or `CONTRIBUTING.md` for building the project — `npm run build` doesn't seem to have [done the trick](https://github.com/ossf/scorecard-monitor/pull/83/commits/9ec23a8be24b5169a475f2b517c4f89d90eee3e6) — so if you could point me in the right direction to get the [source build](https://github.com/ossf/scorecard-monitor/actions/runs/9605577927/job/26493479700) working, that would be super appreciated 🙂

**Review by justaugustus — CHANGES_REQUESTED** [review]
Can you edit to "by OpenSSF Scorecard Monitor"?

**Comment by UlisesGascon** [comment]
Thanks for working on this @lelia!

I just created a contributing guide in https://github.com/ossf/scorecard-monitor/pull/85, based on that `npm run test:update` will fix the issue in the CI as the snapshots are outdated.

**Comment by lelia** [comment]
> Thanks for working on this @lelia!
> 
> I just created a contributing guide in #85, based on that `npm run test:update` will fix the issue in the CI as the snapshots are outdated.

Thanks for the tip @UlisesGascon! Looks like that did the trick 🙂

**Comment by lelia** [comment]
> Can you edit to "by OpenSSF Scorecard Monitor"?

@justaugustus Done!

**Review by UlisesGascon — DISMISSED** [review]
LGTM!

**Review by justaugustus — CHANGES_REQUESTED** [review]
@lelia — Can you rebase and fix the merge conflicts?

I've merged https://github.com/ossf/scorecard-monitor/pull/84 to ensure that there was validation on the `dist/` folder for future PRs (like this one :))

**Review by justaugustus — APPROVED** [review]
Thanks @lelia!

**Pull request merged**
